### ISSUE TITLE
Customize permalink

### ISSUE THREAD

**Issue by longster** [zurb/panini#105]
Is it possible to customize permalink through Front Matter? Ex: from abc.com/about.html to abc.com/about/ ?

**Comment by maxstoyanov** [comment]
As far as I see panini only generates the files you tell it to generate. So there is no way for panini to implement the pattern you want.

Suggestion: Use `.htaccess` to rewrite your incoming URLs and then build your menu to point to the abc.com/about/ page.

**Comment by gakimball** [comment]
Yep, Panini is not a web server, it just builds HTML files. Like @maxstoyanov said, look into using rewrite rules for whatever server you're using. If you're using Foundation's ZURB Template, that would be [BrowserSync](https://browsersync.io/).
