### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by dfrankland** [zurb/panini#109]
There's been a lot of changes and fixes since the last release, is there a possibility that we can get the `npm` module updated with these?

https://github.com/zurb/panini/compare/v1.3.0...master

**Comment by isobar-cupjohn** [comment]
**BUMP**, it would be awesome to see the latest version published.

**Comment by gakimball** [comment]
Done ❤️ 

[Version 1.4.0](https://github.com/zurb/panini/releases/tag/v1.4.0)
