### ISSUE TITLE
Support the preventIndent Handlebars option

### ISSUE THREAD

**Issue by RobDesideri** [zurb/panini#113]
Can you support the **preventIndent** option?
`preventIndent ` solves problems with `pre `and textarea `tags` indentation.
[This is the reference](https://github.com/wycats/handlebars.js/issues/858).

**Comment by gakimball** [comment]
Enabling this all the time seems sensible. Looking at the discussion, I don't see any functional arguments for why you'd need to preserve indent, and the whole `<pre>` thing is definitely a hassle.

We'll do this in 2.0, which is being developed *as we type*, since it's a breaking change.

**Comment by gakimball** [comment]
Addressed in dce628ea39e084ef00c320fa37e5ba4539d9f025, which will ship with v2 of Panini.
