### ISSUE TITLE
Force ignore specific variables

### ISSUE THREAD

**Issue by lcottingham** [zurb/panini#114]
I am templating emails in zurb using the panini variables.
The issue is very simple, the CMS platform I use to distribute these emails also uses the same style of variables i.e. `{{variable_name}}`.

I am templating with variables to ensure that the content is easy to change for each different email template. However, the unsubscribe link or the first name merge field for example will not work and require manual coding after compiling.

The variables that I must use for the CMS system to import the relevant link for unsubscribe is: `{{unsubscribeUrl}}`. If I use this currently, the output is removed and therefore no variable for the CMS to look for.

Can we force panini to ignore specific variables by adding something to the syntax? Perhaps
`{{!variable_name}}` could output {{variable_name}} as a string rather than being processed by panini?

**Comment by gakimball** [comment]
Handlebars has some built-in features to escape expressions. What you're looking for is:

```handlebars
\{{unsubscribeUrl}}
```

Learn more here: <http://handlebarsjs.com/expressions.html> (scroll to the bottom)
