### ISSUE TITLE
Using Panini with Foundation 6.0

### ISSUE THREAD

**Issue by dallasbrands** [zurb/panini#12]
I've downloaded Foundation 6.0, and I'm trying to figure out how to integrate Panini. The folder logic seems a little different from some of the other Foundation documentation. Does anyone have a working example of Foundation 6 with Panini integrated?

**Comment by gakimball** [comment]
We have a template that uses it, called the [ZURB Template](https://github.com/zurb/foundation-zurb-template). You can see how the setup works there.

**Comment by dallasbrands** [comment]
Thanks @gakimball - At the risk of sounding completely ignorent...Is there a version that includes a index.html file? I'm trying to use it directly on a server (not local). What's the easiest way to accomplish this?

**Comment by gakimball** [comment]
There's a [basic template](https://github.com/zurb/foundation-sites-template) that uses a flat file structure, but it also only compiles Sass.

If you wanted to deploy the ZURB Template to a server, you would upload the generated `dist/` folder only, not the entire project.

The [Starter Projects](http://foundation.zurb.com/sites/docs/starter-projects.html) page in the docs explains the functionality of these two templates.

**Comment by dallasbrands** [comment]
@gakimball  - Thanks so much, that's really helpful :+1:
