### ISSUE TITLE
Cache bust assets 

### ISSUE THREAD

**Issue by pablopaul** [zurb/panini#121]
Hey Zurbians,

how do you cache bust assets (css / js / images) within a panini builded prototype?

Do you use a [custom helper](http://foundation.zurb.com/sites/docs/panini.html#custom-helpers) which generates a random version string on every build or so?

**Comment by gakimball** [comment]
Panini doesn't do any static asset manipulation, but you can handle this with a Gulp plugin like [gulp-cache-bust](https://www.npmjs.com/package/gulp-cache-bust). That's what's done on the Foundation documentation, which is powered by Panini.
