### ISSUE TITLE
Panini partials create unwanted whitespace

### ISSUE THREAD

**Issue by davidluhr** [zurb/panini#125]
Panini partials create undesired trailing whitespace, even when no trailing whitespace characters, line breaks, or trailing newlines exist in the partial HTML document.

For example:

`<p>Hello {{> firstName}},</p>` will result in `Hello Foo ,` instead of `Hello Foo,`.

The Handlebars whitespace control syntax (~) has no effect, and `{{> firstName~}}` does resolve this issue.

Thank you for any help with this.

**Comment by gakimball** [comment]
Looks like the code adds a newline: <https://github.com/zurb/panini/blob/master/lib/loadPartials.js#L16>

This code was written long enough ago that I can't remember why I did that, but it doesn't make much sense to me anymore. Most partials are loaded on their own lines anyway, so the extra newline isn't necessary. We can get rid of it.

**Comment by davidluhr** [comment]
Hey Geoff,

Good to know! I appreciate the quick help and I'm glad there's a simple solution.

**Comment by gakimball** [comment]
No prob! I'll try to slip it into a release soon. Need to see if there's anything else worth fixing in the 1.x line, since most of the time I give this project is on [2.0](https://github.com/zurb/panini/tree/v2.0-alt) now.
