### ISSUE TITLE
--dest or --output? confusing

### ISSUE THREAD

**Issue by asselinpaul** [zurb/panini#127]
The CLI tool and repo README mention that --dest should be used but the example (in both cases) uses --output. 

--output works for me so I wonder whether --dest should be changed to --output in the CLI tool and README.

**Comment by asselinpaul** [comment]
If that makes sense, I'll gladly create a pull request.

**Comment by gakimball** [comment]
Yeah, go for it! 👍

**Comment by asselinpaul** [comment]
@gakimball 😄  https://github.com/zurb/panini/pull/128

**Comment by gakimball** [comment]
Fixed via #128, thanks @asselinpaul ❤️
