### ISSUE TITLE
It is possible to use <script type = "x-template"> with panini?

### ISSUE THREAD

**Issue by skruglikov** [zurb/panini#133]
Handlebars.js have **registerHelper()**, **compile()** methods. Does the panini have similar methods? I'm trying to render dynamic content via <script type = "x-template">.

**Comment by gakimball** [comment]
Do you want to use the contents of `<script type="x-template">` to render templates in your JavaScript code, or in Panini?

If you want to use Handlebars in your JavaScript code, wrap your `<script>` element in a raw helper. This will cause Panini to ignore it when it builds your site, so the Handlebars stays the same.

```handlebars
{{{{raw}}}}
<script type="x-template">
  {{!-- Handlebars code... --}}
</script>
{{{{/raw}}}}
```

**Comment by skruglikov** [comment]
I'm want to render templates in JS code and then with Handlebars.compile() to update HTML in DOM. But I have error with Handlebars module.

app.js
```
import $             from 'jquery';
import whatInput     from 'what-input';
import Handlebars    from 'handlebars';
import customInit    from 'customInit';

window.$ = $;

import Foundation from 'foundation-sites';

$(document).foundation();

$(function(){

  // Some Init options
  var options = {};

  // Init setup
  var init = customInit(options);

  // Handlebars setup to render some block
  Handlebars.registerHelper('someFormatter', function(value) {
    return options.someFormatter(value, options);
  });


  $(function() {
    var somePlace = Handlebars.compile($("#some-place").html());
    var someTemplate = Handlebars.compile($("#some-template").html());
    
    function render() {
      var context = {
         init: init()
      };
      somePlace.html(someTemplate(context));
    }

    init.ready(render);
    init.on('changed', render);
  });
});
```

When I try to start npm, I get an error:
```
Message:
    ./~/handlebars/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/lib'
resolve 'fs' in '/Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/lib'
  Parsed request is a module

```

**Comment by gakimball** [comment]
I think the problem is that you're importing the Handlebars npm package, which requires a Node environment. The `Can't resolve 'fs'` error is Handlebars trying to import Node's `fs` module, which doesn't exist in a browser environment.

There is a browser version of Handlebars, so I'd look into how to get `import Handlebars from 'handlebars'` to point to the browser version of Handlebars, instead of the Node version.
