### ISSUE TITLE
Possibility to use characters other than {{ ... }}

### ISSUE THREAD

**Issue by sryze** [zurb/panini#139]
Does Panini allow usage of something other than double curly braces for variables? 

I'm in the process of converting a few dozens of email templates from raw HTML to Foundation for Emails and the templates are also pre-processed by an email service (SendWithUs) after they are built, and it happens to use the same `{{ ... }}` syntax for variables... 

I was wondering if it's possible to switch to some other syntax and make Panini ignore expressions with double curly braces without wrapping everything in `{{{{raw}}}} ... {{{{/raw}}}}` (which is pretty ugly if you ask me).

**Comment by sryze** [comment]
Ignore me, using `\{{ ... }}` seems to work.

**Comment by gakimball** [comment]
Yep! You also can't change the delimiters in Handlebars, so `\{{ ... }}` will be your best bet.

**Comment by charanjit-singh** [comment]
Thanks
