### ISSUE TITLE
Enhancement: Exception Handling causes crash

### ISSUE THREAD

**Issue by ppowalowski** [zurb/panini#14]
handlebar syntax errors or naming typos cause crashing of panini.
If handled properly it could allow fixes without the necessity to restart.

![image_2015-12-01_21-47-39](https://cloud.githubusercontent.com/assets/761221/11513758/3c354df6-9875-11e5-8835-c6ddcad7a5d2.png)

**Comment by gakimball** [comment]
Fixed with #13
