### ISSUE TITLE
Using panini.refresh — typeError in plugin 'run-sequence(server)'

### ISSUE THREAD

**Issue by olegfedak** [zurb/panini#142]
I have the following issue after using panini.refresh in watch task

Default gulp:
```
var gulp = require('gulp');
var runSequence = require('run-sequence');

gulp.task('default', function() {
	runSequence(
		'copy',
		'sass',
		'render',
		'server',
		'copy:watch',
		'sass:watch',
		'render:watch'	
	);
});
```

Server task:
```
var gulp = require('gulp'); 
var browserSync = require('browser-sync').create(); 

gulp.task('server', ['sass:watch', 'render:watch'],  function() { 
    browserSync.init({ 
        server: { 
            baseDir: "dist" 
        },
        files:['dist/*.html', 'dist/css/*.css', 'dist/img/*.*']
    });
});
```

Render is my panini task:
```
var gulp = require('gulp');
var panini = require('panini'); 

gulp.task('render', function() {
  gulp.src('src/pages/**/*.html')
    .pipe(panini({
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      helpers: 'src/helpers/',
      data: 'src/data/'
    }))
    .pipe(gulp.dest('dist'));
});

gulp.task('render:watch', function () {
  gulp.watch(['./src/{layouts,partials,helpers,data}/**/*'], [panini.refresh]);
});
```

It's okay but when I edit partials and save I get the issue:  
**TypeError in plugin 'run-sequence(server)'**

I have tried to change [panini.refresh] at task name ['render'] and don't get error more. but is no any changes after partials files editing — only after server restart

**Comment by olegfedak** [comment]
Just a nice day. I resolved that issue.
Instead `[panini.refresh]` I used `['render' panini.refresh]`

**Comment by gakimball** [comment]
Are the changes being properly updated? I would assume you'd need to do `[panini.refresh, 'render']`, because you want Panini to update itself before the pages re-render.

**Comment by olegfedak** [comment]
All works well. After yours I get:
`Error: pass strings or arrays of strings`

**Comment by gakimball** [comment]
Gotcha, glad it's working 👍
