### ISSUE TITLE
Handlebars noEscape for Panini

### ISSUE THREAD

**Issue by GBratsos** [zurb/panini#144]
Hello all,

I want to ask if there is something like Handlebars noEscape for Panini and if not is there a way to deal with this problem?

My issue, is that i use data from json file and i need to print text from article with html tags inside.

With handlebars, i used this Javascript code:

`        var stone = Handlebars.compile(template, {
          noEscape: true
        })(data[i]);`

Is there something like that on the Gulp build process of Panini?

**Comment by GBratsos** [comment]
Ok i found the solution.

Just use 3 curly braces {{{data.value}}} in order to get rid of double quotes

**Comment by gakimball** [comment]
Good to hear you figured it out 👌
