### ISSUE TITLE
Proposal: add more rendering engines

### ISSUE THREAD

**Issue by mormy** [zurb/panini#16]
Hi,

although I have nothing against Handlebars, I've a real use-case to render not just handlebars, but also a templating engine that would parse jinja2/swig like syntax...

Is this something you guys would be interested in?

Looking at the code now, it shouldn't be too much of a hassle to implement an add-on templating engine, so that HBS remains the default, but if you put a flag like this it replaces hbs with swig, and reuses the data and front-matter from current panini setup.

``` javascript
gulp.task('pages', function() {
  gulp.src('src/pages/**/*.{html,swig}')
    .pipe(panini({
      engine: 'swig', // or jinja2 or whatever developer fancies
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      data: 'src/data/',
      helpers: 'src/helpers/'
    }))
    .pipe(gulp.dest('dist'));
});
```

I'd be more than willing to fork panini, and submit a pull req, but before I dive into it, I'd like to know if you're HBS only, or are you open to suggestions. And integrating with twig/jinja and the rest of temp engines wouldn't be much of a problem then....

Thnx :)

P.S. all inputs and critiques are more than welcome!

**Comment by gakimball** [comment]
We're not hugely interested in building a plugin ecosystem around Panini at the moment, but it sounds like *you* are interested, in which case we can totally support that effort! :)

I think it would be best if other engines are loaded as external libraries, just to keep the core of Panini small. Maybe the configuration can look something like this?

```js
panini({
  engine: requirie('panini-swig')
  // ...
})
```

Or you can probably get clever and parse a string (`swig`) that looks for a specifically-named local package (`panini-swig`).

**Comment by mormy** [comment]
```javascript
panini({
  engine: require('panini-whatever'),
  // ...
});
```
Looks cool, but as I've seen (checked the code, maybe I'm not entirely correct) you have handlebars functions hardcoded into panini, so first order of business would be to drag all handlebars specific stuff out of panini itself, and build a panini-handlebars npm module. 

Shouldn't be much of a problem, but if I do that then I'm effectively responsible for maintaining. Which is not a problem, but ... 

Anyway, I must do this for myself, since we'll use foundation for most projects now in my company, so if I'm successful and it works as a drop-in replacement for this version of panini, that would be great. 

BTW. I love loading data from yml/json, it makes mockups so much easier to do... I'm even considering doing a whole cms based around this... I love it.

**Comment by gakimball** [comment]
If you can make the thing work, we can maintain the Handlebars adapter and you can maintain whatever one you write. For a second, I thought it would be cool to write generic JavaScript functions for those helpers, that the rendering engines tap into, but that's probably more work than it's worth. You could knock out swig versions of those functions pretty easily I think.

My main concern is not overloading this thing with too many features. It's not meant to be a full static site generator, just a simple flat file compiler. We don't have any interest in recreating Jekyll, Metalsmith, Assemble, etc. I think more rendering engines is useful, but beyond that I'm not sure. This tool will be most effective when used as part of a larger build system, like what we do with the [ZURB Template](https://github.com/zurb/foundation-zurb-template).

**Comment by gakimball** [comment]
To follow up on this, using [consolidate.js](https://github.com/tj/consolidate.js/) is probably a simpler alternative to building a plugin architecture.

**Comment by lbineau** [comment]
Any news about this issue ? I would love to see Jade because it remove a lot of markup :)

**Comment by kclarkson** [comment]
@gakimball I too would be interested in seeing the use of consolidate.js as I would like to use Twig templating.  Coming from the Drupal World we use the foundation theme quite a bit would love to build components that worked in both drupal and a static site.

**Comment by gakimball** [comment]
Currently revisiting this.

[Consolidate.js](https://github.com/tj/consolidate.js/) will be the best way to get support for a lot of engines at once. One thing that gets tricky is normalizing features that don't exist in every templating language.

For example, we automatically create Handlebars partials by taking every HTML file in the `partials/` folder and use `handlebars.registerHelper()` to add them. In Pug, partials are defined inline, making this feature trickier to duplicate.

Similarly, Handlebars and Liquid have the concept of filters, where you pipe a value to a function. In Pug, "filters" are just functions on the data object, so it works more like JavaScript.

Consolidate.js doesn't account for all of these disparities, mostly because there's not a clean way to abstract it.

So in certain cases we might need to keep logic specific to a certain rendering engine. Like, we'll keep all the code that automatically loads partials and helpers. And if someone else comes along and wants support for Liquid or Pug or whatever else, we can write custom code for that too, so it still fits Panini's model.

**Comment by gakimball** [comment]
Got the basics of this going in a [v2 branch](https://github.com/zurb/panini/tree/v2.0-alt/engines). Still working on the final implementation; particularly I'm looking at how to reduce the amount of boilerplate for loading and processing files (layouts, partials, helpers, etc.).

**Comment by gakimball** [comment]
The v2 branch now has Pug and EJS engines along with the default of Handlebars. That's a pretty good mix so I'm going to close this for now. If people have suggestions for more, they can drop me a line or write it themselves ;) A simple engine is [fairly straightforward](https://github.com/zurb/panini/blob/70fb2a88bfa3cb64421b7386d5edf7a7f35ca3ac/engines/ejs.js) to write.
