### ISSUE TITLE
Pages with file extensions other than .html cause {{page}} to return the extension

### ISSUE THREAD

**Issue by nwittwer** [zurb/panini#173]
In the normal setup, the file name of the current page is available using `{{page}}`.

For example, `pages/foo.html`. The `{{page}}` value will be the file's name. So it would be: `foo`.

**Problem:**
But if I add a page in another format, such as Handlebars (`pages/bar.hbs`), the returned `{{page}}` is: `bar.hbs` instead of just `bar`.

Is there a way to fix this without modifying the code? After a quick look, https://github.com/zurb/panini/blob/dev/lib/render.js#L55 seems like a suspect for the problem.

**Comment by gakimball** [comment]
Released 1.6.3 to address this 👌
