### ISSUE TITLE
Handlebars helpers are being registered as partials

### ISSUE THREAD

**Issue by Abhra1992** [zurb/panini#2]
In the `index.js` file, you are registering the helpers from the `helpers` folder as Handlebars partials (call to `registerPartial`). Is this by design or did it just get overlooked?

**Comment by Abhra1992** [comment]
There is already an existing [pull request](https://github.com/zurb/panini/pull/1)

**Comment by gakimball** [comment]
Pulled it in, I'll see about releasing a new version today.
