### ISSUE TITLE
Won't accept multiple pages as an argument

### ISSUE THREAD

**Issue by johnellison** [zurb/panini#21]
When I try the following code block (as referenced in ifPage.js):

`
    {{#ifpage 'volunteer', 'academy'}}
`

My CLI returns the following error:

`
Error: Parse error on line 103:
...{#ifpage 'volunteer', 'academy'}}
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
`

I am trying to pass several pages into the ifpage function such that the block is included on more than just one page.

Any insights to making this work would be greatly appreciated.

**Comment by gakimball** [comment]
Parameters in Handlebars functions aren't comma-separated; remove the comma and you'll be good.

**Comment by johnellison** [comment]
You're the man @gakimball thank you.
