### ISSUE TITLE
Add support for subfolder partials with same name

### ISSUE THREAD

**Issue by diesalro** [zurb/panini#22]
If I create a directory under the partials folder called 'Home' and I add a 'banner.html' partial, and then I create another directory at the same level as 'Home' and call it 'Support', and I add another partial which is also called 'banner.html', when importing the partial like {{> banner}}, the latest handlebar partial to be register will always be used, ideally we should be able to do something like: {{> Home/banner}} and {{> Support/banner}} to ensure the proper partial is render.

**Comment by gakimball** [comment]
We can definitely do this.

**Comment by zslabs** [comment]
Would this be similar to sub-folders for pages? It'd be great if I could have a directory structure like:

```
pages/index.html
pages/patterns/index.html
pages/patterns/test.html
```

And have the built structure be:

```
pages/index.html
pages/patterns/index.html
pages/patterns/test/index.html
```

For nicer URLs.

**Comment by gakimball** [comment]
@zslabs Pages copy this way already, as Gulp preserves the filepath when it copies.

**Comment by gakimball** [comment]
FYI this is technically a breaking change, so it'll have to wait until a 2.0 of Panini, but I want to do that in a month or two anyway.

**Comment by arsdehnel** [comment]
Do you have an estimate on when 2.0 might be out?  I'd love to have this feature.

**Comment by alxscms** [comment]
Me too, any news on that?

**Comment by gakimball** [comment]
Implemented in fe386b0606eb76256cdc682b67b426443ddf58ea on the v2 branch.

**Comment by lipis** [comment]
Any estimation for `v2.0`? It would be awesome to have that in.. will it support directories inside the layouts directory as well?

**Comment by gakimball** [comment]
> Any estimation for v2.0?

None right now unfortunately—I haven't had the time to work on it. It's really close, there are a few big things in the way of getting it done.

> will it support directories inside the layouts directory as well?

I hadn't considered this before, but it makes sense to have parity with how partials are included.

**Comment by lipis** [comment]
Should I create an new issue for the layouts subdirectories?

**Comment by gakimball** [comment]
> Should I create an new issue for the layouts subdirectories?

Go for it! 👌
