### ISSUE TITLE
Allow for multiple layouts/pages/partials paths

### ISSUE THREAD

**Issue by avr** [zurb/panini#24]
We have a set of base layouts and partials we use on every project.

We then "override" those layouts/partials with local, identically named versions of each file, if necessary, on a project by project basis.

Would you be open to a PR that allows for loading layouts/partials/pages/helpers from an array of files (vs. a single file path)?  In our workflow, the last loaded file takes precedence.

**Comment by gakimball** [comment]
Sounds good, but keep the configuration directory-based, versus glob-based.

**Comment by avr** [comment]
Thanks for the feedback - here's the PR: https://github.com/zurb/panini/pull/28

**Comment by gakimball** [comment]
Merged in #28
