### ISSUE TITLE
Typo "occured" in render.js error message

### ISSUE THREAD

**Issue by MikeMcC399** [zurb/panini#240]
There is a typo at
https://github.com/foundation/panini/blob/220c821b284459eb852341a3829aa72551a0cbdd/lib/render.js#L80

where "occured" should be written "occurred".

(Reference https://www.merriam-webster.com/dictionary/occurred.)

If you would like a PR to correct this, please let me know, otherwise I would be happy to let a regular contributor to this repository review and make the change if considered necessary.

**Comment by joeworkman** [comment]
Thank you

**Comment by MikeMcC399** [comment]
Since this hasn't been picked up and the project I'm working on which was using Panini is closing down, I'm closing this stale issue.
