### ISSUE TITLE
Order contents of directory by data

### ISSUE THREAD

**Issue by zslabs** [zurb/panini#25]
Hi,
As the title says, is there anything built-in that we could take advantage of for listing; articles for example, by a date specified in the frontmatter of a page?

**Comment by gakimball** [comment]
For reasons explained [here](https://github.com/zurb/foundation-sites/issues/7760#issuecomment-172595375), right now Panini doesn't store any information on individual pages, which means pages can't reference each other.

It's definitely worth exploring, but might have to be saved for a 2.0-ish reworking of the API.

**Comment by gakimball** [comment]
Going to roll this into #47, which is about site-aware data.
