### ISSUE TITLE
Configuration File for layouts

### ISSUE THREAD

**Issue by zslabs** [zurb/panini#26]
If a directory structure has many pages that share a common template, it'd be great if we could specify paths for assuming a specific layout unless otherwise specified.

```
'pages/company/**/*': 'company'
'pages/blog/**/*': 'blog'
```

**Comment by gakimball** [comment]
Definitely interested in exploring this. If you're interested in adding a `pageLayouts` option we're open to a pull request. :)

**Comment by gakimball** [comment]
You can also simplify the configuration by removing the base path, and making it directory-based instead of glob-based.

```
'company': 'company'
'blog': 'blog'
```

Panini knows the root page folder from the `root` setting, so you can join that from the key in the above object to get the final path. `src/pages` + `company`

**Comment by zslabs** [comment]
Cool thanks!
