### ISSUE TITLE
Gulp uncss and production issues

### ISSUE THREAD

**Issue by simonh1000** [zurb/panini#31]
This is not going to be very helpful, but I've been compiling for production and ending up with a css file that was clearly too small, and with big problems in the navbar rendering. I've removed the uncss stage and now everything looks a lot better. I don't know what that part of the code is seeking to do, but wanted to flag for the author and for the community.

**Comment by gakimball** [comment]
Yes, UnCSS has been causing a lot of unintended issues. We have issues open at zurb/foundation-sites#7909 and zurb/foundation-sites#7435 tracking some of them.

For now I'd recommend skipping UnCSS as you have. If you're concerned about file size, remove the CSS for any Foundation component you aren't using.
