### ISSUE TITLE
Only updates on first run of gulp-watch

### ISSUE THREAD

**Issue by Inx51** [zurb/panini#34]
Hi!
Im trying to use the following watch:
gulp.task('watch', function () {
    return gulp.watch(['./src/templates/{layouts,partials,pages}/**/*', './src/{helpers,data}/**/*{.json,.yml}'], ['clean', panini.refresh, 'sass', 'js']);
});
(I have moved my layouts,partials and pages to a different folder..)
However.. this works great when the first watch is triggered.. however.. if I then change any of the files located in the watch.. it doesnt build/compile anything anymore..

Br,
Inx

**Comment by gakimball** [comment]
`panini.refresh()` isn't a proper Gulp task function, so it can't signal to Gulp that it ever finished. That's why it can only run once. Take a look at the [Gulpfile](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.js#L86) for the ZURB Template to see how we implement `panini.refresh()`, particularly the `pages:reset` task.

**Comment by Inx51** [comment]
Hi again, please let me know if there is any other place where we could discuss my issue.. since it might not really be an issue (might very possibly just be me doing something wrong)..
anyway..
I changed my gulp to this:
`var gulp = require('gulp'),
    panini = require('panini'),
    rimraf = require('rimraf');

gulp.task('pages', function () {
    gulp.src('src/templates/pages/**/*.html')
      .pipe(panini({
          root: 'src/templates/pages/',
          layouts: 'src/templates/layouts/',
          partials: 'src/templates/partials/',
          helpers: 'src/helpers/',
          data: 'src/data/'
    }))
    .pipe(gulp.dest('build'));
});

gulp.task('sass', function () {

});

gulp.task('js', function () {

});

gulp.task('clean', function () {

});

gulp.task('pages:reset', function (done) {
    panini.refresh();
    done();
});

gulp.task('pages:reset', function () {
    panini.refresh();
});

gulp.task('vs', ['clean', 'sass', 'js'], function () {

});

gulp.task('build', ['clean', 'pages', 'sass', 'js'], function () {

});

gulp.task('watch', function () {
    return gulp.watch(['./src/templates/{layouts,partials,pages}/**/*', './src/{helpers,data}/**/*{.json,.yml}'], ['pages:reset','pages']);
});`

And Im still having the same issue.. I assume that running pages after pages:reset would result in the same thing as calling gulp.run("pages") from the "pages:reset"-task?

**Comment by gakimball** [comment]
When `gulp.watch()` executes tasks, it starts all of them at the same time, but we need `pages` to run *after* `pages:reset`. There's no way to tell Gulp to run tasks in order after a watch, which is why we use `gulp.run()` instead.

Gulp 4 fixes this issue by allowing you to explicitly define tasks that run in series vs. parallel. We're working on an update to the ZURB Template that uses Gulp 4 and can solve this problem more elegantly. See zurb/foundation-zurb-template#28

**Comment by Inx51** [comment]
Hi again,
I think I have found the issue.. for some reason panini.refresh() is undefined..
Im currently running this gulp-file:
```
var gulp = require('gulp'),
    panini = require('panini'),
    rimraf = require('rimraf'),
    runSequence = require('run-sequence');

gulp.task('pages', function () {
    gulp.src('src/templates/pages/**/*.html')
      .pipe(panini({
          root: 'src/templates/pages/',
          layouts: 'src/templates/layouts/',
          partials: 'src/templates/partials/',
          helpers: 'src/helpers/',
          data: 'src/data/'
    }))
    .pipe(gulp.dest('build'));
});

gulp.task('sass', function () {

});

gulp.task('js', function () {

});

gulp.task('clean', function () {

});

gulp.task('pages:reset', function (done) {
    panini.refresh();
    console.log(panini.refresh());
    done();
});

//gulp.task('pages:reset', function () {
//    panini.refresh();
//});

gulp.task('vs', ['clean', 'sass', 'js'], function () {

});

gulp.task('build', function (callback) {
    runSequence('clean', 'pages:reset', 'pages', 'sass', 'js',
          callback);
});

gulp.task('watch', function () {
    return gulp.watch(['./src/templates/{layouts,partials,pages}/**/*', './src/{helpers,data}/**/*{.json,.yml}'], ['build']);
});
```
Where console.log(panini.refresh()) returns undefined..
any ideas?

Thanks in advance!

**Comment by gakimball** [comment]
`console.log(panini.refresh())` will return undefined, because you're running the function, and it doesn't return a value. `console.log(panini.refresh)` will tell you if the function exists.
