### ISSUE TITLE
Code indenting for markup files incorrect

### ISSUE THREAD

**Issue by basvdijk** [zurb/panini#36]
Take for example http://foundation.zurb.com/sites/docs/panini.html The first line of the HTML code example is correctly indented.

The lines after `<html>` have a huge indent step which is incorrect and makes code disappear outside the box.

I cannot determine if it is a foundation problem or highlight.js

**Comment by gakimball** [comment]
Have you observed this behavior outside of our documentation? I have an issue open at zurb/foundation-sites#8112 to track it.

**Comment by basvdijk** [comment]
Yes I had it in my own project based on foundation docs. That made me look at the zurb live code to see if occurred as well.

**Comment by gakimball** [comment]
The confusing thing is that it only happens on the live servers. Our deploy process has a confirm step between when it compiles the pages and when it deploys, and even then I can't see the indentation issues on my local machine.

**Comment by basvdijk** [comment]
Really weird, I am running OSX btw. I was wondering if could have something todo with an old version of the packages in the package.json

**Comment by gakimball** [comment]
Oh, try this:

```
<!doctype html>
<html>
  <head></head>
  <body>
    <div class="container">
{{> body}}
    </div>
  </body>
</html>
```

If you aren't already, put the `{{> body}}` partial all the way at the edge so there's no indent.

**Comment by basvdijk** [comment]
@gakimball That exactly solved my problem! Thank you so much :+1:
