### ISSUE TITLE
Support for nested layouts

### ISSUE THREAD

**Issue by fivestrokes** [zurb/panini#39]
I am loving this tool. I ran into this scenario and I couldn't make it work:

Scenario: The default layout (default.hbs) contains the main structure of the site. To avoid duplicating the layout in default, I created another layout (aside.hbs) that contains 2 columns that hold the body content and aside items.

aside.hbs
`---`
`layout: default`
`---`
`<section>`
`{{> body }}`
`</section>`

`<aside>`
`list items here`
`</aside>`

index.html uses `layout: default`
news.html uses `layout: aside` > which in turn uses `layout: default`

Is it possible to add support for nested layouts or is it already supported in some way?

**Comment by gakimball** [comment]
Nested layouts aren't in the cards, but you could maybe achieve a similar effect with partials? Look at the [default layout](https://github.com/zurb/foundation-sites/blob/develop/docs/layout/default.html) on the Foundation documentation for an example. The default layout has a bunch of partials that carve up the core elements of the page.

So if your site has multiple layouts, you can drop in partials for the header, footer, even the whole `<head>` tag, to avoid repeating yourself.

**Comment by LandonSchropp** [comment]
I'd like to add that nested layouts would be really helpful for our use case. We're using Panini with Foundation Email, and we have several layouts that would work better if contained inside other layouts.
