### ISSUE TITLE
provide option to disable opening the browser

### ISSUE THREAD

**Issue by timaschew** [zurb/panini#40]
Not sure who does this magic trick if it's panini or https://github.com/zurb/foundation-emails-template or browser-sync, I didn't found the code for it.

But it's annoying when you close the process in the terminal but the browser tab is still open and there is opened another each time you run the gulp job in the terminal again.

**Comment by gakimball** [comment]
That's BrowserSync. In the call to `browser.init()` in your Gulpfile, you can pass the option `open: false`. See: <https://www.browsersync.io/docs/options/#option-open>

**Comment by timaschew** [comment]
thanks
