### ISSUE TITLE
issue with gulp 4

### ISSUE THREAD

**Issue by ibnHamdan** [zurb/panini#42]
Hi 

if my code like this

var gulp        = require('gulp');
var panini = require('panini');

gulp.task('default', function() {
    gulp.src('src/pages/**/*.html')
    .pipe(panini({
        root: 'src/pages/',
        layouts: 'src/layouts/',
        partials: 'src/partials/'
    }))
    .pipe(gulp.dest('build'));
});

the problem in run:  

The following tasks did not complete: default
Did you forget to signal sync completion?

**Comment by gakimball** [comment]
Put a `return` before `gulp.src`. To signal a task being completed, you either have to `return` the stream you made, `return` a Promise, or add a callback to the function and run that.

**Comment by ibnHamdan** [comment]
thanks @gakimball
