### ISSUE TITLE
Iterate over files in /data

### ISSUE THREAD

**Issue by simonh1000** [zurb/panini#43]
I have a large collection of photos that I want to compile to a set of pages of 24 photos. I can write node scripts to divide up the photos and create e.g. json summaries of the files' meta-info to stick in `/data`, but I can't see how to compile that to several pages.

Any suggestions?

 ```
    <div class="row">
        {{#each industrie }}
        <div class="col-sm-3">
            <!--Image Card-->
            <div class="card hoverable">
                <div class="card-image">
                    <div class="view overlay hm-white-slight z-depth-1">
                        <img src="assets/img/industrie/{{this.thumb}}" class="img-responsive" alt="">
                        <a href="#">
                            <div class="mask waves-effect"></div>
                        </a>
                    </div>
                </div>
                <div class="card-content">
                    <h5>Card title</h5>                
                </div>
            </div>
            <!--Image Card-->
        </div>
        {{/each }}
    </div>```

**Comment by gakimball** [comment]
We don't have any hooks to dynamically generate pages. At the moment, assets (pages, partials, etc.) all have to exist on the filesystem to be loaded in.

We don't intend to change this—Panini is meant to be a simple library, and there are larger static site tools that cover more advanced use-cases better.
