### ISSUE TITLE
Can we use YAML frontmatter in files?

### ISSUE THREAD

**Issue by Abhra1992** [zurb/panini#5]
Panini supports YAML data in self-contained `.yml` files. How can one use YAML frontmatter in templates?

**Comment by gakimball** [comment]
You can add Front Matter to any page, and those variables will be available in the page template, as well as the layout template surrounding it.

**Comment by yashilanka** [comment]
Hi i'm new to front matter, and i read all the document related to front matter but i have a problem. how to add custom variable in front matter. i have add the title:something to page and try to render it default layout header title tag with 

{{title}},
{{page.title}}

but none of these method working.. so please explain bit more about how to use custom variable inside frontmatter and render it into layout or partial..

**Comment by gakimball** [comment]
@yashilanka In the page:

```yml
---
breakfasts:
  - eggs
  - bacon
  - toast
---
```

In the HTML for that page (or any layout/partial that uses it):

```handlebars
<ul>
  {{#each breakfasts}}
    <li>{{this}}</li>
  {{/each}}
</ul>
```

If you want to build a more specific data type (like key/value pairs), let me know and I can drum up an example.

**Comment by Jacq** [comment]
Can we use .yml data in front matter block?, such as in global.yml:

`prefix: My Prefix`

and in a specific page front matter block:


```
---
 title: {{global.prefix}} - my page title
---
```



cheers,

**Comment by gakimball** [comment]
@Jacq Handlebars never sees the YAML, so that won't work. What you're trying to do could be done like this, though:

In `layouts/default.html`:

```html
<head>
  <title>{{ global.prefix }} - {{ title }}</title>
</head>
```

In `pages/index.html`:

```yml
---
title: Home
---
```

**Comment by Jacq** [comment]
I ser, thanks!
