### ISSUE TITLE
Support for SVG import

### ISSUE THREAD

**Issue by psullivan6** [zurb/panini#58]
I would love to be able to import an `.svg` file via the handlebars-based import method.

For instance: `{{> icon.svg}}`.

**Comment by tobystokes** [comment]
You can do that as a partial already!

i keep mine in /partials/svg to distinguish from layout segments, but they work just the same.
you can pass them variables too, e.g.
`{{> icon i="expand" size="24" }}`
then in /partials/svg/icon:
`<svg class="icon icon-{{i}}" {{#if size}}style="font-size:{{size}}px"{{/if}}>...svg code...</svg>`

**Comment by psullivan6** [comment]
Thanks @tobystokes. The only way I was able to make this work was by changing the `.svg` file extension to `.html`. Granted, it'll render just fine, I was just hoping to leverage the native `.svg` file extension. Let me know if there's something else I'm missing.

Also, at this point, I'm leveraging the SVG as the `src` attribute of an image tag with a `.jpg` fallback rather than as inline code. - via this [CSS Tricks article](https://css-tricks.com/a-guide-on-svg-support-in-email/)

**Comment by tobystokes** [comment]
Ok, I assumed you wanted to inline the svg, if you want to reference it as an external file, I can't see much benefit in a handlebars helper, just link to it as you would with the jpg.

**Comment by gakimball** [comment]
For Panini v2, I've made a change to the Handlebars engine so that it'll accept files with any extension as a partial. 067c9df14550656504d6dbef6e32c3ae5377e6a3

**Comment by eroffa** [comment]
Use [panini-svg](https://www.npmjs.com/package/panini-svg)
