### ISSUE TITLE
Panini documentation issue: partials section

### ISSUE THREAD

**Issue by grizfan** [zurb/panini#63]
on http://foundation.zurb.com/emails/docs/panini.html, in the "Partials" section, you have the following sample code:

`<body>

```
{{> header}

{{> body}}

{{> footer}}
```

  </body>`

the header partial is missing the closing brace, causing a Gulp error.

**Comment by dereckson** [comment]
Fixed by https://github.com/zurb/foundation-emails/commit/ecef761b0d1c81c801c4427e25801cd37140fd68.
