### ISSUE TITLE
Cannot load .js data file

### ISSUE THREAD

**Issue by ncob** [zurb/panini#68]
Seems like the master branch includes code that the 1.3.0 tag is missing.

The helpful documentation mentions "Data can also be a .js file with a module.exports. The data returned by the export function will be used.", but looking at v1.3.0's lib/loadData.js line 11, only .json and .yml are designated as valid data files:

`var dataFiles = utils.loadFiles(dir, '*.{json,yml}');`

The same line in master:

`var dataFiles = utils.loadFiles(dir, '*.{js,json,yml}');`

Maybe this is intentional, but I found it confusing when reading the documentation and not getting the expected result.

**Comment by gakimball** [comment]
Just published 1.4.0 which has `.js` data loading. 👍
