### ISSUE TITLE
Add documentation of title and varialbles

### ISSUE THREAD

**Issue by rafibomb** [zurb/panini#70]
How adding a title will affect the page
How to add variables and how they work

**Comment by nefeloget** [comment]
**Custom Data**
Custom data can be added to your pages. This data can then be inserted into your HTML through Handlebars. There are two ways to add data to a project.

To add variables to a specific page only, add it at the top of the page's HTML as a[ Front Matter](http://jekyllrb.com/docs/frontmatter/) block. Let's say the below content is inside src/pages/index.html.

```
---
title: Page Title
description: Lorem ipsum.
---

<h1>{{ title }}</h1>
```
http://foundation.zurb.com/sites/docs/panini.html#custom-data

**Comment by gakimball** [comment]
The "Custom Data" section of the Panini docs seems to cover this adequately.
