### ISSUE TITLE
[Feature Request] Copy only modified files to dist folder

### ISSUE THREAD

**Issue by nwittwer** [zurb/panini#77]
My current workflow uploads the `dist` folder directly to my server. Since the Gulp `copy` task always copies all files over, I don't see an easy way to diff the files for changes. Because of that, I have to upload all of the files again (even if they exist on the server, since the timestamp is read as change). 

It would be awesome to be able to copy just the files that have actually been modified into `dist`.

**Comment by nwittwer** [comment]
This may not be the preferred starting point, but here was my solution:

1. Removed `clean` Gulp task (this blocks the ability to diff based on timestamp
2. Added `gulp-changed` package to compare the `src` and `dist` folders and only copy in the newer files
* Useful Gulp pipes: .pipe(changed('dist/assets')) and .pipe(changed('dist/assets/img')) which you can place before the .pipe(gulp.dest()) functions.

After doing so, my build process went from 1min 20s to 10 seconds.

**Comment by jperanson** [comment]
+1

**Comment by gakimball** [comment]
We could add intelligent caching to Panini, but at the moment the library is mostly meant to be used within Gulp, which means we can defer to the various Gulp plugins that can handle revised files in streams.

However, a future version of the library will allow pages to reference each other (e.g., to render a navigation menu), and then built-in caching will be more necessary. See #47
