### ISSUE TITLE
Support for Twig Templating

### ISSUE THREAD

**Issue by kclarkson** [zurb/panini#78]
I am coming over from the Drupal World. And with the Drupal 8 Zurb Theme being one of the top themes, it would be unbelievable to have a Twig templating an option. 

This could allow for easy transition from a prototype to Drupal site.

**Comment by gakimball** [comment]
Closing in favor of #16

[My comment here](https://github.com/zurb/panini/issues/16#issuecomment-284941411) goes into more detail about what multi-language support will look like.
