### ISSUE TITLE
Panini'ing special characters?

### ISSUE THREAD

**Issue by AlchemyUnited** [zurb/panini#83]
For example, I have a word with a #hashtag in my description. Panini will render the description up to that character and then it stops. I tried escaping it but it shows the slash and the #. I just want to the #word. 

TIA

**Comment by kevmul** [comment]
Try wrapping the whole line in double quotes.

**Comment by gakimball** [comment]
In YAML, the hash mark begins a comment. So if you write...

```yaml
title: I love #cats
```

...everything after the `#` is now a comment, and is ignored.

Like @kevmul said, you can wrap the string in quotes and then it'll work.

```yaml
title: 'I love #cats'
```
