### ISSUE TITLE
Menu item in subfolder not working

### ISSUE THREAD

**Issue by kelster44** [zurb/panini#84]
Hello,
I am new to Panini and have an issue where navigation links that are in subfolder are not working. Do all pages need to be in the root directory?
Thank you!

**Comment by gakimball** [comment]
Every page has access to a `{{ root }}` variable which will give you a path prefix appropriate to the current page. Try something like this:

```handlebars
<a href="{{ root }}about.html">About</a>
```

So if you were on `index.html`, the HTML would be:

```html
<a href="about.html">About</a>
```

And if you were on `subfolder/index.html`, the HTML would be:

```html
<a href="../about.html">About</a>
```
