### ISSUE TITLE
How to create and use a helper correct

### ISSUE THREAD

**Issue by XmlmXmlmX** [zurb/panini#95]
I've tried the following examples:

**helpers/foo.js**

```
module.exports = function() {
  return "foo!";
}
```

**...used in partial XY...**

```{{ foo }}``` or ```{{# foo }}{{/ foo }}``` or ```{{# foo }}foofoo?{{/ foo }}```

**...results:**
```
No Output
```

I also tried to use a renamed copy of ```ifPage.js```, and I get this:

```
Panini: rendering error ocurred.
 { [Error: Missing helper: "ifpagenew"]
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'Missing helper: "ifpagenew"',
  name: 'Error',
  number: undefined }
```

![panini_bug.png](https://s16.postimg.org/75auatulx/panini_bug.png)

**Comment by nefeloget** [comment]
**Custom Helpers**
If you don't see the right helper, you can write your own. Add a javascript file to 'src/helpers', add helpers: 'src/helpers' to the Panini process in your gulpfile.babel.js, restart npm, then call it in your templates.

```
// Example file src/helpers/bold.js
module.exports = function(options) {
  // options.fn(this) = Handelbars content between {{#bold}} HERE {{/bold}}
  var bolder = '<strong>' + options.fn(this) + '</strong>';
  return bolder;
}
```

http://foundation.zurb.com/sites/docs/panini.html#custom-helpers

**Comment by callaginn** [comment]
@XmlmXmlmX: Did you ever figure out a solution to this? I ran into a similar "missing helper" error today when I renamed one of my non-working helpers. And info on all this seems spotty or nonexistent : P

**Comment by gakimball** [comment]
@callaginn When you get that "missing helper" error, if you restart your build process, does it go away?

**Comment by callaginn** [comment]
@gakimball: I think I finally realized I had done something stupid. I was still referencing a partial that had gotten renamed in one of about 50 emails.

All our emails, templates, partials, etc have gone through several updates so far, so it's easy to miss something in the chaos. And upgrades pretty much always cause problems : P

**Comment by gakimball** [comment]
@callaginn Good to hear you figured it out! :)

@XmlmXmlmX, I'm going to close this issue. I'm sorry nobody ever got to it when it was opened, but to try and close the book on this:

There's a number of reasons your `foo` helper might not have worked so it's a little tricky to diagnose. It could have been a bug with Panini, or it could have been an issue with the Gulpfile not properly updating Panini's rendering engine when a new helper is added.

And regarding `ifpagenew` not working, there's two issues with your code. First, you have to match the case of the file, so it would be `{{# ifPageNew }}`. Second, that code you copied is actually a function that returns a helper, so it can't be used the way you're using it. If you took the inner function and made *that* the helper, it would do something.
