### ISSUE TITLE
Cannot access variables inside each loop

### ISSUE THREAD

**Issue by negativefix** [zurb/panini#96]
I was trying to construct full paths for set of images using the each loop below. But` {{root}} `and `{{imagepath}}` variables inside the loop output nothing. When moved outside the loop, they work as expected and print their values. BTW this code chunk is inside a partial.

` {{#each leed-images}}
            <img src="{{root}}{{imagepath}}{{this}}.jpg" alt="">
  {{/each}}
`

**Comment by kevmul** [comment]
could you try:
```{{#each lead-images}} <img src="{{this.root}}{{this.imagepath}}{{this.this}}.jpg" alt=""> {{/each}}```
I hope this works.

**Comment by nefeloget** [comment]
`{{#each lead-images}} <img src="{{@root.root}}{{@root.imagepath}}{{this}}.jpg" alt=""> {{/each}}`

**@root**

Initial context that the template was executed with.
```
{{#each array}}
  {{@root.foo}}
{{/each}}
```
Unless explicitly modified this value is consistent across all portions of the page rendering, meaning it's be be used within partials where depthed parameters are unable to reference their parent template.

**Comment by negativefix** [comment]
Thanks for the answers. @root solved my problem.
