### ISSUE TITLE
Adds BOM when using partials

### ISSUE THREAD

**Issue by Inx51** [zurb/panini#98]
Hi!
For some reason once I use my partials panini appears to add a BOM(&#65279) before the rendered partial..

Any ideas?..
I have tried to save all my files as UTF-8.. but that doesn't do it..

**Comment by Inx51** [comment]
Turns out that Visual Studio adds BOM to alot of its created files...
Found an extension for Visual Studio to prevent BOM.. however.. would be nice if panini just stripped that away from partials and layouts..

**Comment by FracturedShader** [comment]
I just ran in to this, and submitted [a fix](https://github.com/zurb/panini/pull/129).

**Comment by gakimball** [comment]
Merged #129.

@FracturedShader, while we're here, do you think you could do the same fix for Panini 2.0? Panini 1.0 is more or less EOL now.

I think there's two places where you'd need to do it.

First off, I'd recommend using the [strip-bom](https://www.npmjs.com/package/strip-bom) library to do it. Keeps the codebase a little more slim :)

For pages, you'd probably want to add BOM stripping [here](https://github.com/zurb/panini/blob/v2.0-alt/lib/render.js#L121), where the page is separated into Front Matter variables and a body. You can where the `page.body` string is returned in this function at the end. You'd want to strip the BOM from `page.body` and return the modified string instead.

For partials, there's one function the library uses to load files and read their contents, which you can see [here](https://github.com/zurb/panini/blob/v2.0-alt/lib/engine.js#L35). Right now the string comes straight from `fs.readFile`, so you can modify that to strip the BOM before returning the file's contents.

**Comment by FracturedShader** [comment]
@gakimball, sure thing! I'll do that after work tonight.

**Comment by gakimball** [comment]
@FracturedShader Awesome, thank you so much! :)

**Comment by gakimball** [comment]
Just published version 1.5.0, which has the BOM stripping.

**Comment by gakimball** [comment]
Merged #131 to get BOM stripping into 2.0.
